//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Ex_Danil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public string Number_Order { get; set; }
        public int ID_Product { get; set; }
        public System.DateTime Data_Of_The_Order { get; set; }
        public int Count { get; set; }
        public int ID_Pickup_Point { get; set; }
        public int ID_Status { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Pickup_Point Pickup_Point { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
